export const API_ENDPOINTS = {
    REGISTER: '/accounts/signup/',
    SENDVERIFICATIONGAMILCODE: '/accounts/send-mail-verify-code/',
    VERIFYCODE: '/accounts/verify-mail/',
    LOGIN: '/accounts/login/',
    // LOGIN: '/accounts/v2/login/mobile/',
    LAWYERNETWORKLIST: '/lawyer-network/lawyers/',
    COUNTRIES: '/accounts/v2/countries/',
    COUNTRIESSEARCH: "accounts/country/",
    COUNTRIESDETAILSSTATES: 'accounts/v2/country/detail',
    ANALYSISCONTRACT: '/ai/analyze-contract/v2/',
    SUPPLIERSLIST: 'agency/agency-profile',
    GOOGLELOGIN: '/accounts/dj-rest-auth/google/',
    CONNECTSUPPLIER: 'accounts/user_connections/',
    INVITEUSER: '/accounts/invite-user/create/',
    SENDACCESSTOKEN: "/accounts/dj-rest-auth/google/",
    ESIGNDOCLIST: "esign/document/",
    GOOGLESIGNUP: '/auth/google/signup/',
    UPDATEUSERPROFILE: 'accounts/user-profile/',
    USERPROFILE: 'accounts/user-profile/',
    FORGETEPASSWORD: 'accounts/forget-password/?resend=true',
    FORGETPASSWORDRESET: 'accounts/forget-password-reset/',
    GETLANGUAGES: 'accounts/languages/',
    GENERATEURL: 'ai/doc/save/',
    AI_REVIEW: 'settings/openai/analyze-contract/',
    LINKEDINLOGIN: 'accounts/dj-rest-auth/linkedin/',
    GETPRIVACYSETTINGS: '/accounts/user-profile/privacy_settings/',
    UPDATEPRIVACYSETTINGS: 'accounts/user-profile/privacy_settings/',
    SUBSCRIPTIONPLANDETAIL: 'subscription/subscription_plans/',
    SUBSCRIPTIONINITIATEPAYMENT: 'subscription/initiate_payment/',
    SUBSCRIPTIONSTATUS: '/subscription/plan-details/',
    SUBSCRIPTIONCANCEL: '/subscription/cancel_subscription/',
    HASPREMIUMDETAILS: 'subscription/plan-details/',
    USERORDERDETAILS: '/subscription/order/?limit=5&offset=0',
    PAYMENTDETAILS: '/subscription/order/payment_detail/',
    DELETEUSERACCOUNT: '/accounts/delete/',
    AIDRAFT: "/settings/openai/analyze-contract/v2/",
    SAVEDRAFTTEMPLATE: 'ai/draft-template/',
    ALLTEMPLATES: '/ai/draft-template/',
    ESIGN: 'esign/document/',
    MSA_ALL_DROPDOWN_LIST_V2: "/msa/v2/msa/all-msa/",
    NEW_AI_DRAFT_V2: "/ai/draft-contract/",
    ADDFAVORITES: 'favorites/favorites/',
    //Organisation Api's endpoint's
    ORGANISATIONDASHBOARDMAP: 'organisation/statistics/main-stats',
    ORGANISATIONDASHBOARD: 'organisation/dashboard/',
    ORGANISATIONUSERPROFILE: 'accounts/user-profile/',
    ORGANISATIONPROFILE: 'organisation/profile/',
    ORGANIZATIONTOPAGENCYDASHBOARD: 'organisation/my-agencies',
    ORGANIZATIONJOBPOSTDASHBOARD: '/job/job-post/',
    ORGANIZATIONUSERMEMBERDASHBOARD: 'organisation/organisation-user/?limit=100',
    MSACONTRACTORLIST: 'msa/v2/master-agreement/contractor',
    MSASERVICELIST: '/msa/v2/master-agreement/service',
    MSAALLSTATUS: 'msa/master-agreement/',
    MSADETAIL: 'msa/master-agreement',
    UPDATEMSA: 'msa/master-agreement',
    MSAFIELDSDROPDOWN: 'msa/msa-fields/',
    CURRENCYDETAILS: 'accounts/currency/',
    GETCURRENCY:'/accounts/currency/',
    PAYMENTTERMSDROPDOWNCREATEMSA: 'settings/payment-terms/',
    MASTERDATALIST: 'masterdata/master-data/',
    APPROVERCUSTOMUSER: '/accounts/custom-user/',
    CREATEMSA: '/msa/master-agreement/',
    SOWCONTRACTORLIST: "sow/v2/statement-of-work/contractor/",
    SOWSERVICELIST: "sow/v2/statement-of-work/service/",
    CREATESOW: "sow/statement-of-work/",
    SOWALLSTATUS: 'sow/statement-of-work/',
    SOWDETAIL: "sow/statement-of-work/",
    SOWFIELDSDROPDOWN: "sow/sow-fields/",
    UPDATESOW: "sow/statement-of-work/",
    TIMESHEET: "timesheet/timesheet/",
    CREATESERVICESOW: "sow/v2/service-statement-of-work/",
    MASTERMATERIALLIST: `masterdata/material-master-data/`,
    MATERIAL_DETAILS: "masterdata/material-master-data",
    UPDATESERVICESOW: "sow/v2/service-statement-of-work/",
    MASTERDTATA: 'masterdata/master-data/',
    // Agency Dashboard endpoint's  
    AGENCYDASHBOARD: 'agency/dashboard-stats/',
    AGENCYPROFILE: 'agency/agency-profile/',
    AGENCYDASHBOARDSECROW: '/agency/dashboard/',
    AGENCYDASHBOARDGRAPHDETAILS: '/agency/revenue-expense/',
    //Lawyer Dashboard endpoint's
    INDIVIDUALUSERSLIST: 'accounts/v2/individual-users/',
    INDIVIDUALUSERSDETAILS: '/accounts/v2/individual-users/',
    TOPRESOURCE: "resources/resources-profile",
    GETORGANISATIONPROFILE: "/organisation/profile",
    JOBPROFILES: "job/public-job-post/relevant-jobs/",
    JOBSLIST:'job/public-job-post/',
    LAWYERPROFILE: 'lawyer-network/profile/',
    RESOURCEPROFILE: '/resources/resources-profile/',
    GOOGLESUBCRIPTION: '/subscription/google-play/confirm/',
    FULLJOBPOST: '/job/job-post',
    CREATEJOBAPPLICATION: 'job/job-application/',
    SKILLDROPDOW: 'resources/skill/',
    RESOURCEDASHBOARD: 'resources/dashboard/',
    GETTALENTUSERPROFILE: '/resources/resources-profile/',
    UPDATETALENTUSERPROFILE: '/resources/resources-profile/',
    SKILLSDROPDOWN: '/resources/skill/',
    AIQUERIES: '/ai/contracts/query/',
    JOBPOST:'/job/job-post/',
    TALENTRESOURCEPROFILEDETAILS:'/resources/resources-profile/',
    TAXGROUPS:'settings/tax-group/',
    COMPANYLOCATION:'settings/company-location/',
    GLACCOUNTS:'settings/gl-account/',
    BUSINESSUNITS:'settings/business-unit/',
    COSTCENTER:'settings/cost-center/',
    LAWYERSPECIALIZATION:'/lawyer-network/specialization/',
    GEMINAI:'/ai/analyze-contract/v2/enhanced/',
    MSAFILED:'/msa/msa-fields/',
    MSATYPE:'/settings/msa-type/',
    UNPSCCODE:'/settings/unpsc-code/',
    TAXRATE:'/settings/tax-service-type/',
    PAYMENTTERMS:'/settings/payment-terms/',
    SOWTYPE:'/settings/sow-type/',
    EXPENSESCATEGORY:'/settings/expense-category/',
    INCOMETAXSLABS:'/settings/tax-slabs/',
    MATERIALMASTERDATA:"/masterdata/material-master-data/",
    APPLELOGIN:'dj-rest-auth/apple/start/'

};
