export const API_ENDPOINTS = {
REGISTER:'/accounts/signup/',
SENDVERIFICATIONGAMILCODE:'/accounts/send-mail-verify-code/',
VERIFYCODE:'/accounts/verify-mail/',
LOGIN: '/accounts/v2/login/mobile/',
LAWYERNETWORKLIST:'/lawyer-network/lawyers/',
COUNTRIES:'/accounts/v2/countries/',
ANALYSISCONTRACT:'/ai/analyze-contract/v2/',
SUPPLIERSLIST:'/organisation/profile/',
GOOGLELOGIN:'/accounts/dj-rest-auth/google/',
CONNECTSUPPLIER:'accounts/user_connections/',
INVITEUSER:'/accounts/invite-user/create/',
SENDACCESSTOKEN:"/accounts/dj-rest-auth/google/",
ESIGNDOCLIST:"esign/document/",
GOOGLESIGNUP:'/auth/google/signup/',
UPDATEUSERPROFILE:'accounts/user-profile/',
USERPROFILE:'accounts/user-profile/',
FORGETEPASSWORD:'accounts/forget-password/?resend=true',
FORGETPASSWORDRESET:'accounts/forget-password-reset/',
GETLANGUAGES:'accounts/languages/',
GENERATEURL:'ai/doc/save/',
AI_REVIEW:'settings/openai/analyze-contract/',
LINKEDINLOGIN:'accounts/dj-rest-auth/linkedin/',
GETPRIVACYSETTINGS:'/accounts/user-profile/privacy_settings',
UPDATEPRIVACYSETTINGS:'accounts/user-profile/privacy_settings/',
SUBSCRIPTIONPLANDETAIL:'subscription/subscription_plans/',
SUBSCRIPTIONINITIATEPAYMENT:'subscription/initiate_payment/',
SUBSCRIPTIONSTATUS:'/subscription/plan-details/',
SUBSCRIPTIONCANCEL:'/subscription/cancel_subscription/',
HASPREMIUMDETAILS:'subscription/plan-details/',
USERORDERDETAILS:'/subscription/order/?limit=5&offset=0',
PAYMENTDETAILS:'/subscription/order/payment_detail/',
  // Add other endpoints here
};
