export const API_ENDPOINTS = {
REGISTER:'/accounts/signup/',
SENDVERIFICATIONGAMILCODE:'/accounts/send-mail-verify-code/',
VERIFYCODE:'/accounts/verify-mail/',
LOGIN:'/accounts/login/',
// LOGIN: '/accounts/v2/login/mobile/',
LAWYERNETWORKLIST:'/lawyer-network/lawyers/',
COUNTRIES:'/accounts/v2/countries/',
COUNTRIESDETAILSSTATES:'accounts/v2/country/detail',
ANALYSISCONTRACT:'/ai/analyze-contract/v2/',
SUPPLIERSLIST:'agency/agency-profile',
GOOGLELOGIN:'/accounts/dj-rest-auth/google/',
CONNECTSUPPLIER:'accounts/user_connections/',
INVITEUSER:'/accounts/invite-user/create/',
SENDACCESSTOKEN:"/accounts/dj-rest-auth/google/",
ESIGNDOCLIST:"esign/document/",
GOOGLESIGNUP:'/auth/google/signup/',
UPDATEUSERPROFILE:'accounts/user-profile/',
USERPROFILE:'accounts/user-profile/',
FORGETEPASSWORD:'accounts/forget-password/?resend=true',
FORGETPASSWORDRESET:'accounts/forget-password-reset/',
GETLANGUAGES:'accounts/languages/',
GENERATEURL:'ai/doc/save/',
AI_REVIEW:'settings/openai/analyze-contract/',
LINKEDINLOGIN:'accounts/dj-rest-auth/linkedin/',
GETPRIVACYSETTINGS:'/accounts/user-profile/privacy_settings',
UPDATEPRIVACYSETTINGS:'accounts/user-profile/privacy_settings/',
SUBSCRIPTIONPLANDETAIL:'subscription/subscription_plans/',
SUBSCRIPTIONINITIATEPAYMENT:'subscription/initiate_payment/',
SUBSCRIPTIONSTATUS:'/subscription/plan-details/',
SUBSCRIPTIONCANCEL:'/subscription/cancel_subscription/',
HASPREMIUMDETAILS:'subscription/plan-details/',
USERORDERDETAILS:'/subscription/order/?limit=5&offset=0',
PAYMENTDETAILS:'/subscription/order/payment_detail/',
DELETEUSERACCOUNT:'/accounts/delete/',
AIDRAFT:"/settings/openai/analyze-contract/v2/",
SAVEDRAFTTEMPLATE:'ai/draft-template/',
ALLTEMPLATES:'/ai/draft-template/',

//Organisation Api's endpoint's
ORGANISATIONDASHBOARD:'organisation/dashboard/',
ORGANISATIONUSERPROFILE:'accounts/user-profile/',
ORGANISATIONPROFILE:'organisation/profile/',
ORGANIZATIONTOPAGENCYDASHBOARD:'organisation/my-agencies',
ORGANIZATIONJOBPOSTDASHBOARD:'/job/job-post/',      
ORGANIZATIONUSERMEMBERDASHBOARD:'organisation/organisation-user',
MSACONTRACTORLIST:'msa/v2/master-agreement/contractor',
MSASERVICELIST:'/msa/v2/master-agreement/service',
MSAALLSTATUS:'msa/master-agreement/',
MSADETAIL:'msa/master-agreement',
UPDATEMSA:'msa/master-agreement',
MSAFIELDSDROPDOWN:'msa/msa-fields/',
CURRENCYDETAILS:'accounts/currency/',
PAYMENTTERMSDROPDOWNCREATEMSA:'settings/payment-terms/',
MASTERDATALIST:'masterdata/master-data/',
APPROVERCUSTOMUSER:'/accounts/custom-user',
CREATEMSA:'/msa/master-agreement/',

SOWCONTRACTORLIST:"sow/v2/statement-of-work/contractor/",
SOWSERVICELIST:"sow/v2/statement-of-work/service/",
SOWALLSTATUS:'sow/statement-of-work/',
SOWDETAIL:"sow/statement-of-work/",
SOWFIELDSDROPDOWN:"sow/sow-fields/",
UPDATESOW:"sow/statement-of-work/",
// Agency Dashboard endpoint's  
AGENCYDASHBOARD:'agency/dashboard-stats/',

//Lawyer Dashboard endpoint's
TOPRESOURCE:"resources/resources-profile",
GETORGANISATIONPROFILE:"/organisation/profile",


JOBPROFILES:"job/public-job-post/relevant-jobs/"
 
};
