// dataArrays.ts

export const actsArray = [
   {
    value: "asper-indian-compliance",
    label: "Indian compliance",
  },
  {
    value: "asper-eiDAS-compliance",
    label: "eiDAs compliance",
  },
  {
    value: "asper-eSign-UETA-compliance",
    label: "eSign UETA compliance",
  },
  {
    value: "asper-aicpa-soc2-compliance",
    label: "AICPA SOC 2 compliance",
  },
  { value: "asper-iso-compliance", label: "ISO compliance", },
  { value: "asper-gdpr-compliance", label: "GDPR compliance",  },
  {
    value: "asper-ccpa-ready-compliance",
    label: "CCPA READY compliance",
  },
  {
    value: "asper-pdpa-ready-compliance",
    label: "PDPA READY compliance",
  },
  {
    value: "asper-lgpd-ready-compliance",
    label: "LGPD READY compliance",
  },
];

export const contractTypeArray = [
   { label: "NON-DISCLOSURE AGREEMENTS", value: "NON-DISCLOSURE AGREEMENTS" },
  { label: "CONFIDENTIALITY AGREEMENT", value: "CONFIDENTIALITY AGREEMENT" },
  { label: "CONSULTING AGREEMENT", value: "CONSULTING AGREEMENT" },
  { label: "SERVICE AGREEMENT", value: "SERVICE AGREEMENT" },
  { label: "COMMISSION AGREEMENT", value: "COMMISSION AGREEMENT" },
  { label: "DISTRIBUTION AGREEMENTS", value: "DISTRIBUTION AGREEMENTS" },
  {
    label: "EMPLOYEE DEPUTATION AGREEMENTS",
    value: "EMPLOYEE DEPUTATION AGREEMENTS",
  },
  { label: "SECONDMENT AGREEMENT", value: "SECONDMENT AGREEMENT" },
  { label: "FINANCE GUARANTEE", value: "FINANCE GUARANTEE" },
  { label: "PERFORMANCE GUARANTEE", value: "PERFORMANCE GUARANTEE" },
  { label: "INDEMNITY BOND", value: "INDEMNITY BOND" },
  { label: "POWER OF ATTORNEY", value: "POWER OF ATTORNEY" },
  {
    label: "JOINT DEVELOPMENT AGREEMENTS",
    value: "JOINT DEVELOPMENT AGREEMENTS",
  },
  { label: "JOINT VENTURE AGREEMENTS", value: "JOINT VENTURE AGREEMENTS" },
  {
    label: "LICENSE AGREEMENTS (TECHNOLOGY OR IPR)",
    value: "LICENSE AGREEMENTS (TECHNOLOGY OR IPR)",
  },
  {
    label: "PURCHASE AND SALE AGREEMENTS",
    value: "PURCHASE AND SALE AGREEMENTS",
  },
  {
    label: "SHARES PURCHASE AND SALE AGREEMENTS",
    value: "SHARES PURCHASE AND SALE AGREEMENTS",
  },
  {
    label: "SALE AND PURCHASE OF EQUIPMENT",
    value: "SALE AND PURCHASE OF EQUIPMENT",
  },
  {
    label: "INSTALLATION AGREEMENT OF THE EQUIPMENT",
    value: "INSTALLATION AGREEMENT OF THE EQUIPMENT",
  },
  {
    label: "SERVICE AGREEMENT OF THE EQUIPMENT",
    value: "SERVICE AGREEMENT OF THE EQUIPMENT",
  },
  { label: "EPC CONTRACT", value: "EPC CONTRACT" },
  {
    label: "POWER PURCHASE AGREEMENT (OPEN ACCESS, TRADING ETC.)",
    value: "POWER PURCHASE AGREEMENT (OPEN ACCESS, TRADING ETC.)",
  },
  { label: "WARRANTY DOCUMENTS", value: "WARRANTY DOCUMENTS" },
  {
    label: "ADVERTISING SERVICE AGREEMENT",
    value: "ADVERTISING SERVICE AGREEMENT",
  },
  { label: "MEDIA SERVICE AGREEMENT", value: "MEDIA SERVICE AGREEMENT" },
  {
    label: "TECHNOLOGY COLLABORATION AGREEMENT",
    value: "TECHNOLOGY COLLABORATION AGREEMENT",
  },
  { label: "LOGISTICS AGREEMENT", value: "LOGISTICS AGREEMENT" },
  { label: "TRANSPORT AGREEMENT", value: "TRANSPORT AGREEMENT" },
  { label: "FREIGHT AGREEMENT", value: "FREIGHT AGREEMENT" },
  {
    label: "RAW MATERIALS SUPPLY AGREEMENTS (INDIGENOUS OR IMPORTS)",
    value: "RAW MATERIALS SUPPLY AGREEMENTS (INDIGENOUS OR IMPORTS)",
  },
  { label: "PRIVATE LABEL AGREEMENTS", value: "PRIVATE LABEL AGREEMENTS" },
  { label: "BROKER AGREEMENTS", value: "BROKER AGREEMENTS" },
  { label: "DEEDS", value: "DEEDS" },
  { label: "EASEMENTS", value: "EASEMENTS" },
  { label: "LEASES", value: "LEASES" },
  { label: "OPTION AGREEMENTS", value: "OPTION AGREEMENTS" },
  { label: "SETTLEMENT AGREEMENTS", value: "SETTLEMENT AGREEMENTS" },
  { label: "SEVERANCE AGREEMENTS", value: "SEVERANCE AGREEMENTS" },
  { label: "SUBCONTRACT AGREEMENTS", value: "SUBCONTRACT AGREEMENTS" },
  { label: "JOB WORK AGREEMENTS", value: "JOB WORK AGREEMENTS" },
  { label: "CONTRACT MANUFACTURING", value: "CONTRACT MANUFACTURING" },
  {
    label: "BUYING AND SELLING OF IMMOVABLE PROPERTY",
    value: "BUYING AND SELLING OF IMMOVABLE PROPERTY",
  },
  { label: "BANKING FACILITY AGREEMENT", value: "BANKING FACILITY AGREEMENT" },
  { label: "LEAVE & LICENSE AGREEMENT", value: "LEAVE & LICENSE AGREEMENT" },
  { label: "LEASE AGREEMENT", value: "LEASE AGREEMENT" },
  { label: "RENT AGREEMENT", value: "RENT AGREEMENT" },
  {
    label: "OVERRIDING COMMISSION AGREEMENT",
    value: "OVERRIDING COMMISSION AGREEMENT",
  },
  {
    label: "ANNUAL RATED CONTRACT (MRO CONTRACTS)",
    value: "ANNUAL RATED CONTRACT (MRO CONTRACTS)",
  },
];

export const countryDataArray = [
  { value: "afghanistan", label: "Afghanistan" },
  { value: "albania", label: "Albania" },
  { value: "algeria", label: "Algeria" },
  { value: "andorra", label: "Andorra" },
  { value: "angola", label: "Angola" },
  { value: "antigua_and_barbuda", label: "Antigua and Barbuda" },
  { value: "argentina", label: "Argentina" },
  { value: "armenia", label: "Armenia" },
  { value: "australia", label: "Australia" },
  { value: "austria", label: "Austria" },
  { value: "azerbaijan", label: "Azerbaijan" },
  { value: "bahamas", label: "Bahamas" },
  { value: "bahrain", label: "Bahrain" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "barbados", label: "Barbados" },
  { value: "belarus", label: "Belarus" },
  { value: "belgium", label: "Belgium" },
  { value: "belize", label: "Belize" },
  { value: "benin", label: "Benin" },
  { value: "bhutan", label: "Bhutan" },
  { value: "bolivia", label: "Bolivia" },
  { value: "bosnia_and_herzegovina", label: "Bosnia and Herzegovina" },
  { value: "botswana", label: "Botswana" },
  { value: "brazil", label: "Brazil" },
  { value: "brunei", label: "Brunei" },
  { value: "bulgaria", label: "Bulgaria" },
  { value: "burkina_faso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cabo_verde", label: "Cabo Verde" },
  { value: "cambodia", label: "Cambodia" },
  { value: "cameroon", label: "Cameroon" },
  { value: "canada", label: "Canada" },
  { value: "central_african_republic", label: "Central African Republic" },
  { value: "chad", label: "Chad" },
  { value: "chile", label: "Chile" },
  { value: "china", label: "China" },
  { value: "colombia", label: "Colombia" },
  { value: "comoros", label: "Comoros" },
  { value: "congo", label: "Congo" },
  { value: "costa_rica", label: "Costa Rica" },
  { value: "croatia", label: "Croatia" },
  { value: "cuba", label: "Cuba" },
  { value: "cyprus", label: "Cyprus" },
  { value: "czech_republic", label: "Czech Republic" },
  { value: "denmark", label: "Denmark" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominica", label: "Dominica" },
  { value: "dominican_republic", label: "Dominican Republic" },
  { value: "east_timor", label: "East Timor" },
  { value: "ecuador", label: "Ecuador" },
  { value: "egypt", label: "Egypt" },
  { value: "el_salvador", label: "El Salvador" },
  { value: "equatorial_guinea", label: "Equatorial Guinea" },
  { value: "eritrea", label: "Eritrea" },
  { value: "estonia", label: "Estonia" },
  { value: "eswatini", label: "Eswatini" },
  { value: "ethiopia", label: "Ethiopia" },
  { value: "fiji", label: "Fiji" },
  { value: "finland", label: "Finland" },
  { value: "france", label: "France" },
  { value: "gabon", label: "Gabon" },
  { value: "gambia", label: "Gambia" },
  { value: "georgia", label: "Georgia" },
  { value: "germany", label: "Germany" },
  { value: "ghana", label: "Ghana" },
  { value: "greece", label: "Greece" },
  { value: "grenada", label: "Grenada" },
  { value: "guatemala", label: "Guatemala" },
  { value: "guinea", label: "Guinea" },
  { value: "guinea_bissau", label: "Guinea-Bissau" },
  { value: "guyana", label: "Guyana" },
  { value: "haiti", label: "Haiti" },
  { value: "honduras", label: "Honduras" },
  { value: "hungary", label: "Hungary" },
  { value: "iceland", label: "Iceland" },
  { value: "india", label: "India" },
  { value: "indonesia", label: "Indonesia" },
  { value: "iran", label: "Iran" },
  { value: "iraq", label: "Iraq" },
  { value: "ireland", label: "Ireland" },
  { value: "italy", label: "Italy" },
  { value: "ivory_coast", label: "Ivory Coast" },
  { value: "jamaica", label: "Jamaica" },
  { value: "japan", label: "Japan" },
  { value: "jordan", label: "Jordan" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kenya", label: "Kenya" },
  { value: "kiribati", label: "Kiribati" },
  { value: "kosovo", label: "Kosovo" },
  { value: "kuwait", label: "Kuwait" },
  { value: "kyrgyzstan", label: "Kyrgyzstan" },
  { value: "laos", label: "Laos" },
  { value: "latvia", label: "Latvia" },
  { value: "lebanon", label: "Lebanon" },
  { value: "lesotho", label: "Lesotho" },
  { value: "liberia", label: "Liberia" },
  { value: "libya", label: "Libya" },
  { value: "liechtenstein", label: "Liechtenstein" },
  { value: "lithuania", label: "Lithuania" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malawi", label: "Malawi" },
  { value: "malaysia", label: "Malaysia" },
  { value: "maldives", label: "Maldives" },
  { value: "mali", label: "Mali" },
  { value: "malta", label: "Malta" },
  { value: "marshall_islands", label: "Marshall Islands" },
  { value: "mauritania", label: "Mauritania" },
  { value: "mauritius", label: "Mauritius" },
  { value: "mexico", label: "Mexico" },
  { value: "micronesia", label: "Micronesia" },
  { value: "moldova", label: "Moldova" },
  { value: "monaco", label: "Monaco" },
  { value: "mongolia", label: "Mongolia" },
  { value: "montenegro", label: "Montenegro" },
  { value: "morocco", label: "Morocco" },
  { value: "mozambique", label: "Mozambique" },
  { value: "myanmar", label: "Myanmar" },
  { value: "namibia", label: "Namibia" },
  { value: "nauru", label: "Nauru" },
  { value: "nepal", label: "Nepal" },
  { value: "netherlands", label: "Netherlands" },
  { value: "new_zealand", label: "New Zealand" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigeria" },
  { value: "north_korea", label: "North Korea" },
  { value: "north_macedonia", label: "North Macedonia" },
];

export const businessLineArray = [
  { value: "Real estate", label: "Real estate" },
  { value: "india", label: "Procurement" },
  { value: "sales", label: " Sales" },
  { value: "financeAccounting", label: "Finance & Accounting" },
  { value: "hr", label: " Human Resources" },
  { value: "production", label: "Production" },
  { value: "qualityAssurance", label: "Quality Assurance" },
  { value: "maintenance", label: "Maintenance" },
  { value: "vendorManagement", label: "Vendor Management" },
  { value: "inventoryManagement", label: "Inventory Management" },
  { value: "logisticsWarehousing", label: "Logistics & Warehousing" },
  { value: "supplyChainManagement", label: "Supply Chain Management" },
  { value: "marketing", label: "Marketing" },
  { value: "costing", label: "Costing" },
  { value: "payroll", label: "Payroll" },
  { value: "itErpManagement", label: "IT & ERP Management" },
  { value: "legalCompliance", label: "Legal & Compliance" },
  { value: "hse", label: "Health, Safety & Environment (HSE)" },
  { value: "researchDevelopment", label: "Research & Development (R&D)" },
  { value: "businessStrategy", label: "Business Strategy" },
  { value: "customerService", label: "Customer Service" },
  { value: "others", label: "Others" },
];
